name: Hello World
author: Juan Betancourt
description: Some description
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: Juan
outputs:
  time:
    description: "The greeting time"
runs:
  using: "node12"
  main: "dist/index.js"
