on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2
      - uses: /.github/actions/hello
        id: hello
        with:
          who-to-greet: "Juan Betancourt"
      - run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
