on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          pwd
          ls -lh ./.github/actions/slack
      - name: Send a slack Message
        uses: ./.github/actions/slack
        with:
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          message: Hello Crazy PHP world
      - uses: ./.github/actions/issue
        id: issue
        with:
          token: ${{ secrets.TOKEN_GITHUB}}
          title: Super Title for the issue
          body: Body
          assignees: |
            juanjo44
      - run: |
          echo ${{ steps.issue.outputs.issue }}
      - run: chmod +x .github/actions/hello-docker/entrypoint.sh
      - uses: ./.github/actions/hello-docker
        id: hello
        with:
          who-to-greet: "Juan Betancourt"
      - run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
          echo $HELLO
