name: CI
on:
  pull_request:
    branches: [develop]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm ci
      - name: Check Code Formatting
        run: npm run format:check
      - name: Run Automated Tests
        run: npm test -- --coverage
        env:
          CI: true
